### ISSUE TITLE
Б11. При наполнении контентом элементы каждой версии страницы соответствуют макету.

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy-adaptive/2288595-sedona-28#11]
Убери для этих `legend`овпаддинги
![image](https://github.com/htmlacademy-adaptive/2288595-sedona-28/assets/47776594/d774106b-2879-4b1e-800e-dce5e8934fcb)

**Comment by baileys-li** [comment]
@natty-dv

**Comment by natty-dv** [comment]
Вроде как все поправила по обоим замечаниям
